CREATE DATABASE db_rest_api;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    pass VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


